### ISSUE TITLE
Adding xpaths

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#128]
I've added all my xpaths but whenever I try to insert the links, I get this error for every link: 

```
Traceback (most recent call last):
  File "tests/test_golden.py", line 384, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 198, in insert_golden_tests
    meta = metahtml.parse(html, url)
  File "./metahtml/__init__.py", line 60, in parse
    meta_best, meta_all = parse_all(html, url, fast=True)
  File "./metahtml/__init__.py", line 25, in parse_all
    meta_best['timestamp_published'], meta_all['timestamp_published'] = timestamp.get_timestamp_published(parser, url, fast=fast)
  File "./metahtml/timestamp.py", line 492, in get_timestamp_published
    return get_timestamp(html, url, xpaths, use_url_date=True, **kwargs)
  File "./metahtml/timestamp.py", line 550, in get_timestamp
    for hostname,xpath in xpaths:
ValueError: too many values to unpack (expected 2)
```

Not sure what to do

**Comment by mikeizbicki** [comment]
This error is in due to the xpaths not being entered in the correct format somehow.  The error is happening on line 550, and that line is looping over all of the xpaths in the list.  It is expected that each expect be a tuple with exactly two elements (the hostname and the xpath), and the error message is telling you that your list is not in that format.
