### ISSUE TITLE
UnicodeDecodeError when running the URL_FILE command

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#14]
Hi All! When I ran the command
```
$cat URLS_FILE | xargs python3 tests/test_golden.py --insert_urls
```
I got:
```
Traceback (most recent call last):
  File "tests/test_golden.py", line 174, in <module>
    @pytest.mark.parametrize('test',get_golden_tests())
  File "tests/test_golden.py", line 158, in get_golden_tests
    for test in csv.DictReader(f, dialect='excel', strict=True):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 111, in __next__
    self.fieldnames
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 1414: invalid start byte
```
Has anyone else run into this problem/ found a way to fix it? 

Thanks!

**Comment by mikeizbicki** [comment]
One of the webpages is likely formatted weird, and it would be okay to just ignore that one webpage if you can figure out which one it is.  We might need to meet over zoom to fix this.

**Comment by rayegleekel** [comment]
@mikeizbicki Okay, that makes sense. I am having a few issues so I think a zoom may be helpful. I am around today until 4pm PST and anytime tomorrow, if you have any time.

**Comment by mikeizbicki** [comment]
I'm on the zoom link right now if you're able to drop in.
