### ISSUE TITLE
Found unknown parsers in the "PARSERS" setting: base-formats

### ISSUE THREAD

**Issue by n8stringham** [mikeizbicki/metahtml#184]
Hi @Tonnpo @mikeizbicki ,

I started working on the initial 50 content annotations today by first running 

`$ python3 tests/test_content.py --lang=en --username=n8stringham`

This worked fine and I think I was able to successfully annotate the first 3 articles as I can see them in `tests/.golden`. 
When the 4th article was getting served to me, the program quit with this error message.
```
INFO:root:get_unannotated_common_urls()
INFO:root:len(unannotated_urls)=49
INFO:root:/Users/nstringham/projects/contributions/metahtml/tests/.golden/http___www.danielpipes.org_186_the-ayatollah-the-novelist-and-the-weste8eba86c/2020-06-29
{
    "language": "en-us",
    "timestamp.published": {
        "hi": "1997-07-25 00:00:00.999999",
        "lo": "1997-07-25 00:00:00"
    },
    "type": "article",
    "url": "http://www.danielpipes.org/186/the-ayatollah-the-novelist-and-the-west"
}
INFO:metahtml:compiling adblock rules (this may take a while)
Traceback (most recent call last):
  File "/Users/nstringham/projects/contributions/metahtml/tests/test_content.py", line 284, in <module>
    run(annotate_content)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/Users/nstringham/projects/contributions/metahtml/tests/test_content.py", line 153, in annotate_content
    annotate_content_url(url, username)
  File "/Users/nstringham/projects/contributions/metahtml/tests/test_content.py", line 239, in annotate_content_url
    meta = metahtml.parse(html, url, extractor_config=extractor_config)
  File "./metahtml/__init__.py", line 124, in parse
    calculate_property('timestamp.published')
  File "./metahtml/__init__.py", line 122, in calculate_property
    parser.meta[property_name] = module.Extractor.extract(parser)
  File "./metahtml/property/__common__.py", line 259, in extract
    result = cls.str_to_result(result_str)
  File "./metahtml/property/timestamp/__common__.py", line 291, in str_to_result
    timestamp_lo = dateparser.parse(
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/__init__.py", line 51, in parse
    parser = DateDataParser(languages=languages, locales=locales,
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/conf.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/date.py", line 358, in __init__
    check_settings(settings)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/conf.py", line 231, in check_settings
    extra_check(setting_name, setting_value)
  File "/Users/nstringham/miniconda3/envs/metahtml/lib/python3.9/site-packages/dateparser/conf.py", line 124, in _check_parsers
    raise SettingValidationError(
dateparser.conf.SettingValidationError: Found unknown parsers in the "PARSERS" setting: base-formats
```
If I try to rerun 
`$ python3 tests/test_content.py --lang=en --username=n8stringham`
I continue to get the error.

Seems like something to do with the `dateparser` package. I have version `1.0.0`
Any ideas?

**Comment by Tonnpo** [comment]
It seems like base-formats has been removed for `1.0.0`. Please see scrapinghub/dateparser#721.

**Comment by mikeizbicki** [comment]
You shouldn't be using version 1.0.0.  The `requirements.txt` specifies
```
dateparser==0.7.4
```
If this library is not the correct version, then it's likely that other libraries are also not the correct version.  The easiest way to fix this would be to create a venv and run `pip3 install -r requirements.txt` inside the venv.  Otherwise, you'll be doing a lot of manually deleting and installing libraries as these types of errors come up.
