### ISSUE TITLE
Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by valenxie** [mikeizbicki/metahtml#187]
Hi Mike @mikeizbicki , I was annotating the articles then the program was stopped by this error:
`selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver`
The full description of the error is here:
```
INFO:metahtml:compiling adblock rules (this may take a while)
INFO:langid.langid:initializing identifier
Traceback (most recent call last):
  File "tests/test_content.py", line 284, in <module>
    run(annotate_content)
  File "/Users/ValenXie/anaconda3/lib/python3.7/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ValenXie/anaconda3/lib/python3.7/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/Users/ValenXie/anaconda3/lib/python3.7/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "tests/test_content.py", line 153, in annotate_content
    annotate_content_url(url, username)
  File "tests/test_content.py", line 254, in annotate_content_url
    firefox = selenium.webdriver.Firefox()
  File "/Users/ValenXie/anaconda3/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Users/ValenXie/anaconda3/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
```
I was wondering if the error is related to some misconfigurations in network, but it was working just fine a few minutes ago.

**Comment by mikeizbicki** [comment]
This error message looks like python cannot start firefox for some reason.  I don't believe it would be related to network configurations/availability, but I could see misconfigured packages causing this error.  I'm not sure why things would suddenly stop working if it was previously working, however.

Possibly this was just a transient issue and will resolve itself.  If not, reinstalling the packages is my best idea for fixing.
