### ISSUE TITLE
Recursion depth

### ISSUE THREAD

**Issue by maxinebaghdadi** [mikeizbicki/metahtml#24]
Hi!

A common problem I've been having with some of the links pertains to the recursion depth. I've been getting the following error: 

`RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by mikeizbicki** [comment]
Without the full stack trace I can't help

**Comment by maxinebaghdadi** [comment]
`(base) wl-196-230:metahtml maxinebaghdadi$ python3 tests/test_golden.py --insert_urls https://abc14news.com/2020/04/21/during-the-coronavirus-crisis-how-is-north-korea-really-handling-its-zero-cases/
`
```

downloading url= https://abc14news.com/ ... Traceback (most recent call last):
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10e47e160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='abc14news.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e47e160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_golden.py", line 362, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 141, in insert_golden_tests
    get_cached_webpages(new_url,None)
  File "tests/test_golden.py", line 91, in get_cached_webpages
    download_url()
  File "tests/test_golden.py", line 80, in download_url
    r = requests.get(url,headers={'User-Agent':'NovichenkoBot'},verify=False)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='abc14news.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e47e160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
(base) wl-196-230:metahtml maxinebaghdadi$ python3 tests/test_golden.py --insert_urls https://abcnews.go.com/International/speculations-surround-north-korean-leader-kim-jong-uns/story?id=70261581
/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
downloading url= https://abcnews.go.com/ ... done.
/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
downloading url= https://abcnews.go.com/International/ ... done.
/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
downloading url= https://abcnews.go.com/International/speculations-surround-north-korean-leader-kim-jong-uns/ ... error: status_code= 404
/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
downloading url= https://abcnews.go.com/International/speculations-surround-north-korean-leader-kim-jong-uns/story? ... error: status_code= 404
/Users/maxinebaghdadi/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
downloading url= https://abcnews.go.com/International/speculations-surround-north-korean-leader-kim-jong-uns/story?id=70261581 ... done.
Traceback (most recent call last):
  File "tests/test_golden.py", line 362, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 245, in insert_golden_tests
    insert_golden_tests(new_urls2, overwrite, verbose=False, insert_altlang_urls=insert_altlang_urls)
  File "tests/test_golden.py", line 245, in insert_golden_tests
    insert_golden_tests(new_urls2, overwrite, verbose=False, insert_altlang_urls=insert_altlang_urls)
  File "tests/test_golden.py", line 245, in insert_golden_tests
    insert_golden_tests(new_urls2, overwrite, verbose=False, insert_altlang_urls=insert_altlang_urls)
  [Previous line repeated 982 more times]
  File "tests/test_golden.py", line 188, in insert_golden_tests
    meta = metahtml.parse(html, url)
  File "./metahtml/__init__.py", line 59, in parse
    meta_best, meta_all = parse_all(html, url, fast=True)
  File "./metahtml/__init__.py", line 24, in parse_all
    meta_best['timestamp_published'], meta_all['timestamp_published'] = timestamp.get_timestamp_published(parser, url, fast=fast)
  File "./metahtml/timestamp.py", line 379, in get_timestamp_published
    return get_timestamp(html, url, xpaths, use_url_date=True, **kwargs)
  File "./metahtml/timestamp.py", line 442, in get_timestamp
    for element in parser.xpath(xpath):
  File "src/lxml/etree.pyx", line 1574, in lxml.etree._Element.xpath
  File "src/lxml/xpath.pxi", line 261, in lxml.etree.XPathElementEvaluator.__init__
  File "src/lxml/xpath.pxi", line 133, in lxml.etree._XPathEvaluatorBase.__init__
  File "src/lxml/xpath.pxi", line 57, in lxml.etree._XPathContext.__init__
  File "src/lxml/extensions.pxi", line 94, in lxml.etree._BaseContext.__init__

```

**Comment by mikeizbicki** [comment]
It looks like the problem is that this hostname doesn't exist anymore, so you should skip it.

I'll try to make the error messages for this type of problem more informative for the future.
