### ISSUE TITLE
Error when adding any URL

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#64]
When I try to add a URL like usual, I get this error: 
```
pdimitrov@lambda-server:~/metahtml$ python3 tests/test_golden.py --insert_urls https://fortune.com/2020/04/21/asia-markets-drop-reports-north-korea-kim-jong-un-health-grave-danger/
Traceback (most recent call last):
  File "tests/test_golden.py", line 384, in <module>
    insert_golden_tests(urls, args.overwrite, args.verbose)
  File "tests/test_golden.py", line 160, in insert_golden_tests
    if row['url']==url or row['url']==url+'/' or row['url']+'/'==url:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
This is the case for any URL I try to add. Any ideas how to fix this? Thank you

**Comment by mikeizbicki** [comment]
Hmm... I remember people getting that error the first week.  IIRC, the problem was that their `golden.csv` file had gotten corrupted.  I think either the header line got deleted somehow, or there was an extra line somewhere in the file like `>>>>>>>` left over from a merge conflict.

**Comment by peter-dimitrov** [comment]
There was in fact one line that said "Updated >>>>>" and another that looked like this: "========". I removed both of these lines, but I am still getting the same error. Any other ideas? Or is this something we should debug over zoom? Thanks

**Comment by mikeizbicki** [comment]
My guess is that there are still more lines like that resulting from the merge conflict.  I'm happy to look at it on zoom with you tomorrow if you'd like.  I'll be on at 10am.

**Comment by peter-dimitrov** [comment]
I ended up copy and pasting the raw golden.csv file from the repo to replace the golden.csv I had before, and it seems to be working now. Do you think doing so is fine, or could this cause other issues?
